// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: inventory.sql

package database

import (
	"context"
)

const newInventoryProduct = `-- name: NewInventoryProduct :one
INSERT INTO inventory (product_type_id, location_id, stock)
VALUES ($1, $2, $3)
RETURNING id, product_type_id, location_id, stock
`

type NewInventoryProductParams struct {
	ProductTypeID int64 `json:"product_type_id"`
	LocationID    int64 `json:"location_id"`
	Stock         int32 `json:"stock"`
}

func (q *Queries) NewInventoryProduct(ctx context.Context, arg NewInventoryProductParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, newInventoryProduct, arg.ProductTypeID, arg.LocationID, arg.Stock)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.ProductTypeID,
		&i.LocationID,
		&i.Stock,
	)
	return i, err
}

const updateInventoryStock = `-- name: UpdateInventoryStock :one
UPDATE inventory
SET stock = stock + $3
WHERE product_type_id = $1
AND location_id = $2
RETURNING id, product_type_id, location_id, stock
`

type UpdateInventoryStockParams struct {
	ProductTypeID int64 `json:"product_type_id"`
	LocationID    int64 `json:"location_id"`
	Stock         int32 `json:"stock"`
}

func (q *Queries) UpdateInventoryStock(ctx context.Context, arg UpdateInventoryStockParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, updateInventoryStock, arg.ProductTypeID, arg.LocationID, arg.Stock)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.ProductTypeID,
		&i.LocationID,
		&i.Stock,
	)
	return i, err
}
