// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: inventory.sql

package database

import (
	"context"
)

const listInventoryByLocation = `-- name: ListInventoryByLocation :many
SELECT i.id, i.product_type_id, i.location_id, i.stock, pt.name, pt.code, pt.img
FROM inventory i
inner join product_types pt on i.product_type_id = pt.id
WHERE location_id = $1
`

type ListInventoryByLocationRow struct {
	ID            int64   `json:"id"`
	ProductTypeID int64   `json:"product_type_id"`
	LocationID    int64   `json:"location_id"`
	Stock         int32   `json:"stock"`
	Name          string  `json:"name"`
	Code          string  `json:"code"`
	Img           *string `json:"img"`
}

func (q *Queries) ListInventoryByLocation(ctx context.Context, locationID int64) ([]ListInventoryByLocationRow, error) {
	rows, err := q.db.Query(ctx, listInventoryByLocation, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInventoryByLocationRow
	for rows.Next() {
		var i ListInventoryByLocationRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductTypeID,
			&i.LocationID,
			&i.Stock,
			&i.Name,
			&i.Code,
			&i.Img,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newInventoryProduct = `-- name: NewInventoryProduct :one
INSERT INTO inventory (product_type_id, location_id, stock)
VALUES ($1, $2, $3)
RETURNING id, product_type_id, location_id, stock
`

type NewInventoryProductParams struct {
	ProductTypeID int64 `json:"product_type_id"`
	LocationID    int64 `json:"location_id"`
	Stock         int32 `json:"stock"`
}

func (q *Queries) NewInventoryProduct(ctx context.Context, arg NewInventoryProductParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, newInventoryProduct, arg.ProductTypeID, arg.LocationID, arg.Stock)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.ProductTypeID,
		&i.LocationID,
		&i.Stock,
	)
	return i, err
}

const updateInventoryStock = `-- name: UpdateInventoryStock :one
UPDATE inventory
SET stock = stock + $3
WHERE product_type_id = $1
AND location_id = $2
RETURNING id, product_type_id, location_id, stock
`

type UpdateInventoryStockParams struct {
	ProductTypeID int64 `json:"product_type_id"`
	LocationID    int64 `json:"location_id"`
	Stock         int32 `json:"stock"`
}

func (q *Queries) UpdateInventoryStock(ctx context.Context, arg UpdateInventoryStockParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, updateInventoryStock, arg.ProductTypeID, arg.LocationID, arg.Stock)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.ProductTypeID,
		&i.LocationID,
		&i.Stock,
	)
	return i, err
}
