// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: locations.sql

package database

import (
	"context"
)

const addLocation = `-- name: AddLocation :one
INSERT INTO locations(location)
VALUEs ($1)
RETURNING id, location
`

func (q *Queries) AddLocation(ctx context.Context, location string) (Location, error) {
	row := q.db.QueryRow(ctx, addLocation, location)
	var i Location
	err := row.Scan(&i.ID, &i.Location)
	return i, err
}

const getLocationByName = `-- name: GetLocationByName :one
SELECT id
FROM locations
WHERE location = $1
`

func (q *Queries) GetLocationByName(ctx context.Context, location string) (int64, error) {
	row := q.db.QueryRow(ctx, getLocationByName, location)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listLocations = `-- name: ListLocations :many
SELECT id, location
FROM locations
ORDER BY location
`

func (q *Queries) ListLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.Query(ctx, listLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(&i.ID, &i.Location); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
