// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

type Inventory struct {
	ID            int64 `json:"id"`
	ProductTypeID int64 `json:"product_type_id"`
	LocationID    int64 `json:"location_id"`
	Stock         int32 `json:"stock"`
}

type Location struct {
	ID              int64   `json:"id"`
	Location        string  `json:"location"`
	Address         string  `json:"address"`
	SiteDesc        string  `json:"site_desc"`
	AdditionalNotes *string `json:"additional_notes"`
	Img             []byte  `json:"img"`
}

type ProductTagList struct {
	ID          int64  `json:"id"`
	ProductType string `json:"product_type"`
	Epchex      string `json:"epchex"`
}

type ProductType struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Code string `json:"code"`
	Img  []byte `json:"img"`
}

type User struct {
	ID           int64   `json:"id"`
	Username     string  `json:"username"`
	Email        *string `json:"email"`
	PasswordHash []byte  `json:"password_hash"`
	Role         string  `json:"role"`
	LocationID   *int64  `json:"location_id"`
}
