// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: product_type.sql

package database

import (
	"context"
)

const getProductTypeByName = `-- name: GetProductTypeByName :one
SELECT id, name, code, img_url
FROM product_types
WHERE name=$1
`

func (q *Queries) GetProductTypeByName(ctx context.Context, name string) (ProductType, error) {
	row := q.db.QueryRow(ctx, getProductTypeByName, name)
	var i ProductType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.ImgUrl,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, code, img_url
FROM product_types
ORDER BY id
`

func (q *Queries) ListProducts(ctx context.Context) ([]ProductType, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductType
	for rows.Next() {
		var i ProductType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.ImgUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newProduct = `-- name: NewProduct :one
INSERT INTO product_types (name, code, img_url)
VALUES ($1, $2, $3)
RETURNING id, name, code, img_url
`

type NewProductParams struct {
	Name   string  `json:"name"`
	Code   string  `json:"code"`
	ImgUrl *string `json:"img_url"`
}

func (q *Queries) NewProduct(ctx context.Context, arg NewProductParams) (ProductType, error) {
	row := q.db.QueryRow(ctx, newProduct, arg.Name, arg.Code, arg.ImgUrl)
	var i ProductType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.ImgUrl,
	)
	return i, err
}
