// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: product_type.sql

package database

import (
	"context"
)

const newProduct = `-- name: NewProduct :one
INSERT INTO product_types (name, code)
VALUES ($1, $2)
RETURNING id, name, code
`

type NewProductParams struct {
	Name string `json:"name"`
	Code string `json:"code"`
}

func (q *Queries) NewProduct(ctx context.Context, arg NewProductParams) (ProductType, error) {
	row := q.db.QueryRow(ctx, newProduct, arg.Name, arg.Code)
	var i ProductType
	err := row.Scan(&i.ID, &i.Name, &i.Code)
	return i, err
}
