// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: product_tag_list.sql

package database

import (
	"context"
)

const addProductTagList = `-- name: AddProductTagList :one
INSERT INTO product_tag_list (product_type, epcHex)
VALUES ($1, $2)
RETURNING id, product_type, epchex
`

type AddProductTagListParams struct {
	ProductType string `json:"product_type"`
	Epchex      string `json:"epchex"`
}

func (q *Queries) AddProductTagList(ctx context.Context, arg AddProductTagListParams) (ProductTagList, error) {
	row := q.db.QueryRow(ctx, addProductTagList, arg.ProductType, arg.Epchex)
	var i ProductTagList
	err := row.Scan(&i.ID, &i.ProductType, &i.Epchex)
	return i, err
}

const listProductTagList = `-- name: ListProductTagList :many
SELECT ptl.product_type, ptl.epcHex
FROM product_tag_list ptl
ORDER BY product_type
`

type ListProductTagListRow struct {
	ProductType string `json:"product_type"`
	Epchex      string `json:"epchex"`
}

func (q *Queries) ListProductTagList(ctx context.Context) ([]ListProductTagListRow, error) {
	rows, err := q.db.Query(ctx, listProductTagList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductTagListRow
	for rows.Next() {
		var i ListProductTagListRow
		if err := rows.Scan(&i.ProductType, &i.Epchex); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
