// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: users.sql

package database

import (
	"context"
)

const getUserByUsername = `-- name: GetUserByUsername :one

SELECT id, username, email, password_hash, role, location_id
FROM users
WHERE username = $1
`

// -- name: GetUserByEmail :one
// SELECT *
// FROM users
// WHERE email = $1;
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.LocationID,
	)
	return i, err
}

const mapUserIDToLocationID = `-- name: MapUserIDToLocationID :one
UPDATE users
SET location_id = $1
WHERE id = $2
RETURNING id, username, email, password_hash, role, location_id
`

type MapUserIDToLocationIDParams struct {
	LocationID *int64 `json:"location_id"`
	ID         int64  `json:"id"`
}

func (q *Queries) MapUserIDToLocationID(ctx context.Context, arg MapUserIDToLocationIDParams) (User, error) {
	row := q.db.QueryRow(ctx, mapUserIDToLocationID, arg.LocationID, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.LocationID,
	)
	return i, err
}

const mapUserToLocationName = `-- name: MapUserToLocationName :one
UPDATE users
SET location_id = (SELECT l.id from locations l where l.location = $1)
WHERE users.id = (SELECT u.id from users u where u.username=$2)
RETURNING id, username, email, password_hash, role, location_id
`

type MapUserToLocationNameParams struct {
	Location string `json:"location"`
	Username string `json:"username"`
}

func (q *Queries) MapUserToLocationName(ctx context.Context, arg MapUserToLocationNameParams) (User, error) {
	row := q.db.QueryRow(ctx, mapUserToLocationName, arg.Location, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.LocationID,
	)
	return i, err
}
